DROP TABLE IF EXISTS RiderPost;

CREATE TABLE IF NOT EXISTS RiderPost (
  PostingID INT NOT NULL,
  AreaID INT NULL,
  PosterID INT NOT NULL,
  RideDate DATETIME NOT NULL,
  LeaveTime DATETIME NOT NULL,
  ReturnTime DATETIME NOT NULL,
  OfferedGasMoney DECIMAL(5,2) NULL,
  PRIMARY KEY (PostingID)
)